# Config ver 1.4

# Set to "true" if you want to completely cover the censored word..
fullCensorship: false
# Enable link blocking in chat?
block-links: true

use-punishment: true
swear-word-thresholds:
  5: "warn {player} 10m 'Too many swear words!'"
  10: "kick {player} 'Repeated use of swear words!'"
  15: "ban {player} 1d 'Swear word limit exceeded!'"

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true

# Debug mode
debug: false