# Config ver 1.3

# Set to "true" if you want to completely cover the censored word..
fullCensorship: false

# Wy6bór języka pluginu. Możliwe wartości: "EN", "PL"
# TODO: language: "EN"

# Ustawienia sprawdzania i automatycznej aktualizacji
# TODO: checkForUpdates: true
# TODO: autoDownloadUpdates: false

stats:
  enabled: true

# Debug mode
debug: false