# Config ver 1.7.0

# Plugin language selection. Possible values:  EN, PL
# If you would like to add your own language file, please contact us on Discord (https://discord.gg/Zk6mxv7eMh).
language: "EN"

# Set to "true" if you want to completely cover the censored word.
fullCensorship: false

# Enable link blocking in chat?
block-links: true

use-punishment: true # Use command execution for offensive language?
swear-word-thresholds:  # Set your own commands to be applied after a specific number of detected swear words. We recommend our punishment plugin – PunisherX.
  5: "warn {player} 1d Too many swear words!"
  10: "mute {player} 15m Repeated use of swear words!"
  15: "ban {player} 1d Swear word limit exceeded!"

message:
  no-link: "<red>Sharing links in the chat is not allowed on this server!"

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Debug mode set to true provides more detailed logs in the console. Use only in case of problems!
debug: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true