# Config ver 1.3

# Set to "true" if you want to completely cover the censored word..
fullCensorship: false

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true

# Debug mode
debug: false