# Config ver 1.2

# Ustaw true jeśli chcesz zakrywać w całości cenzurowane słowo.
fullCensorship: false

# Wy6bór języka pluginu. Możliwe wartości: "EN", "PL"
# TODO: language: "EN"

# Ustawienia sprawdzania i automatycznej aktualizacji
# TODO: checkForUpdates: true
# TODO: autoDownloadUpdates: false

# Tryb debugowania ustawiony na true daje więcej opisów działań w konsoli
debug: false