name: CleanerX
version: '${version}'
main: pl.syntaxdevteam.cleanerx.CleanerX

api-version: '1.20'
folia-supported: true
softdepend: [Folia]

authors: [SyntaxDevTeam]
description: A sophisticated plugin designed to filter and replace inappropriate language with censored alternatives or remove it entirely, ensuring a clean and respectful gaming environment.
website: https://github.com/SyntaxDevTeam
